// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
	"time"
)

const clearEntries = `-- name: ClearEntries :exec
DELETE FROM entries
`

func (q *Queries) ClearEntries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearEntries)
	return err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (domain, username, encrypted_password, created_at)
VALUES (
    ?1,
    ?2,
    ?3,
	?4
)
RETURNING id, domain, username, encrypted_password, created_at
`

type CreateEntryParams struct {
	Domain            string
	Username          string
	EncryptedPassword []byte
	CreatedAt         time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Domain,
		arg.Username,
		arg.EncryptedPassword,
		arg.CreatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Username,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :one
DELETE FROM entries
WHERE domain = ?1 AND username = ?2
RETURNING id, domain, username, encrypted_password, created_at
`

type DeleteEntryParams struct {
	Domain   string
	Username string
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, deleteEntry, arg.Domain, arg.Username)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Username,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, domain, username, encrypted_password, created_at
FROM entries
WHERE domain = ?1 AND username = ?2
`

type GetEntryParams struct {
	Domain   string
	Username string
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, arg.Domain, arg.Username)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Username,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, domain, username, encrypted_password, created_at
FROM entries
ORDER BY domain ASC, username ASC
`

func (q *Queries) ListEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Username,
			&i.EncryptedPassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreEntry = `-- name: RestoreEntry :one
INSERT INTO entries (id, domain, username, encrypted_password, created_at)
VALUES (
    ?1,
    ?2,
    ?3,
	?4,
    ?5
)
RETURNING id, domain, username, encrypted_password, created_at
`

type RestoreEntryParams struct {
	ID                int64
	Domain            string
	Username          string
	EncryptedPassword []byte
	CreatedAt         time.Time
}

func (q *Queries) RestoreEntry(ctx context.Context, arg RestoreEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, restoreEntry,
		arg.ID,
		arg.Domain,
		arg.Username,
		arg.EncryptedPassword,
		arg.CreatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Username,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET encrypted_password = ?3
WHERE domain = ?1 AND username = ?2
RETURNING id, domain, username, encrypted_password, created_at
`

type UpdateEntryParams struct {
	Domain            string
	Username          string
	EncryptedPassword []byte
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry, arg.Domain, arg.Username, arg.EncryptedPassword)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Username,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}
