// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package db

import (
	"context"
)

const getMetadata = `-- name: GetMetadata :one
SELECT value
FROM metadata
WHERE key = ?1
`

func (q *Queries) GetMetadata(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const setMetadata = `-- name: SetMetadata :exec
INSERT INTO metadata (key, value)
VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetMetadataParams struct {
	Key   string
	Value []byte
}

func (q *Queries) SetMetadata(ctx context.Context, arg SetMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setMetadata, arg.Key, arg.Value)
	return err
}
