// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Entry struct {
	ID                int64
	Domain            string
	Username          string
	EncryptedPassword []byte
	CreatedAt         time.Time
}

type Metadata struct {
	Key   string
	Value []byte
}
